version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URI: postgresql://username:password@db/mydatabase
    depends_on:
      - db

volumes:
  postgres_data:
